version: "3"
services:
  sqldb:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superrootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    healthcheck: # health checks required to prevent application from starting before database.
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            
  app:
    build: .
    depends_on:
      sqldb:
        condition: service_healthy
    ports:
    - 8000:8000
    env_file:
      - .env
    # Uncomment out lines below for local development
    # volumes:
    #   - ./simpledinein:/app
    #   - ./setup.sh:/setup.sh
    # command: /setup.sh