FROM python:latest
WORKDIR /app
COPY setup.sh setup.sh
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt 
COPY simpledinein/ .
EXPOSE 8000
ARG DJANGO_SUPERUSER_USERNAME
ARG DJANGO_SUPERUSER_EMAIL
ARG DJANGO_SUPERUSER_PASSWORD
ENV DJANGO_SUPERUSER_USERNAME = ${DJANGO_SUPERUSER_USERNAME}
ENV DJANGO_SUPERUSER_EMAIL = ${DJANGO_SUPERUSER_EMAIL}
ENV DJANGO_SUPERUSER_PASSWORD = ${DJANGO_SUPERUSER_PASSWORD}
ENTRYPOINT [ "./setup.sh" ]